### ISSUE TITLE
Is there a local cache in ossindex-maven-plugin like the one in ossindex-gradle-plugin?

### ISSUE THREAD

**Issue by gwenneg** [sonatype/ossindex-maven#21]
Using a local cache with ossindex-maven-plugin would help me fixing rate limiting issues.

The [ossindex-gradle-plugin doc](https://github.com/OSSIndex/ossindex-gradle-plugin#cache) mentions a local cache which is not documented in the ossindex-maven-plugin doc. Does it exist?

**Comment by jdillon** [comment]
@gwenneg the maven-plugin presently does not have any persistent cache; only an in-memory volatile cache (which wouldn't help much for getting past rate limiting).

**Comment by ken-duck** [comment]
FYI, we are exploring adding a cache to the plugin. Authenticated connections, as jdillon suggests, will still definitely help with the problem even if/when a cache is implemented.

**Comment by gwenneg** [comment]
@jdillon I've been running tests on a few projects using an anonymous connection for now, but I'm pretty sure the 64 requests per hour limit announced in the [ossindex-gradle-plugin doc](https://github.com/OSSIndex/ossindex-gradle-plugin#credentials) will be a problem for me without a cache implementation in ossindex-maven-plugin.

@ken-duck I'm glad to read that!

**Comment by jdillon** [comment]
btw I've mostly gotten a local persistent cache working; have to do a bit more testing on some other platforms (windows mostly is what I think may be a problem); but hopefully early next year this will be mergeable.

**Comment by jdillon** [comment]
@gwenneg 3.0.3 has been released which has a default persistent directory-based cache; should be up in central shortly; give it a whirl and report back if you can please :-)

**Comment by gwenneg** [comment]
@jdillon Great! Thanks for this new version. I will test it as soon as possible.

**Comment by gwenneg** [comment]
It looks like there's some kind of lock issue while using the cache with Windows 10:

```
[WARNING] Failed to load entry: C:\Users\gwenneg\AppData\Local\Sonatype\Ossindex\report-cache\93\39\9339e50e1b387122c85c1032b9fe94e7beb97b43
java.nio.file.FileSystemException: C:\Users\gwenneg\AppData\Local\Sonatype\Ossindex\report-cache\93\39\9339e50e1b387122c85c1032b9fe94e7beb97b43: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.expireEntry(DirectoryCache.java:208)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.access$1(DirectoryCache.java:206)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache$1.apply(DirectoryCache.java:177)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache$1.apply(DirectoryCache.java:1)
	at org.sonatype.ossindex.service.client.util.FileLocker.lock(FileLocker.java:62)
	at org.sonatype.ossindex.service.client.util.FileLocker.readLock(FileLocker.java:75)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.loadEntry(DirectoryCache.java:172)
	at org.sonatype.ossindex.service.client.cache.DirectoryCache.getIfPresent(DirectoryCache.java:116)
	at org.sonatype.ossindex.service.client.internal.OssindexClientImpl.requestComponentReports(OssindexClientImpl.java:150)
	at org.sonatype.ossindex.maven.common.ComponentReportAssistant.request(ComponentReportAssistant.java:85)
	at org.sonatype.ossindex.maven.plugin.AuditMojo.execute(AuditMojo.java:246)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

I only had time to run a few builds with the new version of the plugin and this happened several times. It didn't seem to prevent OSS Index from scanning vulnerabilities (maybe the REST API call was made because the cache was not working?).

**Comment by jdillon** [comment]
@gwenneg thx for trying; I had a feeling windows would be a bit of a problem... :-\

**Comment by jdillon** [comment]
@gwenneg I found a few problems with locking on windows; if you have time if you could give 3.0.4-SNAPSHOT a try and report back it would be helpful.

You'll probably need to add:

```
  <repositories>
    <repository>
      <id>sonatype-public</id>
      <url>https://repository.sonatype.org/content/groups/sonatype-public-grid/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>sonatype-public</id>
      <url>https://repository.sonatype.org/content/groups/sonatype-public-grid/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
```

... to access our snapshot repository.

**Comment by jdillon** [comment]
3.0.4 is released; if would be helpful if you could poke at it
